# Generated by Django 4.2.1 on 2023-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
